# This service message contains normalized image plane coordinates of
# newly-elevated models for the purpose of reacquiring the correct ID of
# tracks that have been occluded or out of frame.

float64 x   # new track x position (normalized image plane)
float64 y   # new track y position (normalized image plane)

---

uint32  id  # returned track id
