# Service message for any R-RANSAC node specific parameters. This allows
# Items in the Visual Frontend Dynamic Reconfigure to propagate to the
# R-RANSAC node.

float32 published_video_scale       # Scale of output video topic

bool feature_outliers_enabled       # Status of source
bool difference_image_enabled       # Status of source

# add source info here: noise, etc