# All default param values are to be saved in a file like this. Such values
# have first priority in rqt_reconfigure. The yaml is loaded at launch.

###############################################################################
#### Visual Frontend Node

# intrinsic camera parameters
# (only used when tracking in normalized image coordinates)
# (future: 2 camera matrices, one for each image size.
# distortion coefficients are static and can be used for resized image)
# NOT DYNAMICALLLY RECONFIGURABLE
visual_frontend/calibration/fx: 1348.206365
visual_frontend/calibration/fy: 1347.862463
visual_frontend/calibration/cx: 351.089626
visual_frontend/calibration/cy: 272.416355
visual_frontend/calibration/k1: 0
visual_frontend/calibration/k2: 0
visual_frontend/calibration/k3: 0
visual_frontend/calibration/k4: 0
visual_frontend/calibration/k5: 0
visual_frontend/calibration/k6: 0
visual_frontend/calibration/p1: 0
visual_frontend/calibration/p2: 0

# general processing
visual_frontend/frame_stride: 3
visual_frontend/downsize_scale: 0.8

# homography
visual_frontend/reprojection_error: 1.0

# feature manager
visual_frontend/feature_type:    "GFTT"
visual_frontend/matching_method: "LK"
visual_frontend/points_max:      2000
visual_frontend/points_target:   1200
visual_frontend/corner_quality:       0.03  # NOT DYNAMICALLLY RECONFIGURABLE, AUTOMATICALLY ADJUSTED IN ALGORITHM
visual_frontend/corner_quality_min:   0.03  # NOT DYNAMICALLLY RECONFIGURABLE
visual_frontend/corner_quality_max:   0.05  # NOT DYNAMICALLLY RECONFIGURABLE
visual_frontend/corner_quality_alpha: 0.999 # NOT DYNAMICALLLY RECONFIGURABLE
visual_frontend/pyramid_size: 21            # NOT DYNAMICALLLY RECONFIGURABLE

# source_features
visual_frontend/minimum_pixel_velocity: 1
visual_frontend/maximum_pixel_velocity: 10

###############################################################################
#### R-RANSAC Node

# general
rransac/dt: 1

# R-RANSAC specific parameters
rransac/Nw: 10
rransac/M: 30
rransac/tauR: 50.0
rransac/sigmaR_pos: 5.0
rransac/sigmaR_vel: 1.0
rransac/rransac_motion_model: 2

# RANSAC specific parameters
rransac/ell: 100
rransac/guided_sampling_threshold: 1000
rransac/tauR_RANSAC: 50.0
rransac/gamma: 0.5
rransac/sigmaR_pos_RANSAC: 5.0
rransac/ransac_motion_model: 0

# model merging parameters
rransac/tau_vel_percent_diff: 0.25
rransac/tau_vel_abs_diff: 900.0
rransac/tau_angle_abs_diff: 15.0
rransac/tau_xpos_abs_diff: 50.0
rransac/tau_ypos_abs_diff: 50.0

# model pruning parameters
rransac/frame_cols: 2000
rransac/frame_rows: 2000
rransac/tau_CMD_prune: 10

# track (i.e., good model) parameters
rransac/tau_rho: 0.6
rransac/tau_CMD: 4
rransac/tau_Vmax: 30.0
rransac/tau_T: 4