# All default param values are to be saved in a file like this. Such values
# have first priority in rqt_reconfigure. The yaml is loaded at launch.

###############################################################################
#### Visual Frontend Node

# general processing
visual_frontend/frame_stride: 2
visual_frontend/resize_scale: 0.4
visual_frontend/published_video_scale: 1.0
visual_frontend/published_frame_stride: 1.0
visual_frontend/text_scale: 1.0

# feature manager
visual_frontend/lkt_tracker_enabled:    0
visual_frontend/lkt_tracker_max_features:      2000
visual_frontend/parallax_comp: false
visual_frontend/parallax_threshold: 0.003

# feature motion
visual_frontend/feature_motion_enabled: true
visual_frontend/feature_motion_sigmaR_pos: 0.007
visual_frontend/feature_motion_sigmaR_vel: 0.0014
visual_frontend/minimum_feature_velocity: 0.002
visual_frontend/maximum_feature_velocity: 0.02

# difference image
visual_frontend/difference_image_enabled: true
visual_frontend/difference_extra_plots: false
visual_frontend/difference_image_sigmaR_pos: 0.007
visual_frontend/blur_kernel: 4
visual_frontend/blur_sigma: 8.0
visual_frontend/threshold: 130
visual_frontend/morph_size: 1
visual_frontend/morph_iterations: 2
visual_frontend/min_complexity: 10
visual_frontend/max_complexity: 100

# Darknet
visual_frontend/darknet_enabled: false
visual_frontend/darknet_threshold: 0.3
visual_frontend/darknet_frame_stride: 3
visual_frontend/darknet_draw_detections: false

# Color Detector
visual_frontend/color_detector_enabled: false
visual_frontend/color_detector_min_hue: 1
visual_frontend/color_detector_max_hue: 179
visual_frontend/color_detector_min_sat: 1
visual_frontend/color_detector_max_sat: 255
visual_frontend/color_detector_min_val: 1
visual_frontend/color_detector_max_val: 255
visual_frontend/color_detector_morph_iterations: 1
visual_frontend/color_detector_morph_kernel: 5
visual_frontend/color_detector_min_blob_size: 200
visual_frontend/color_detector_max_blob_size: 1000

# transform manager
visual_frontend/simple_homography_enabled: true

# recognition manager
visual_frontend/recognition_type: 0
visual_frontend/crop_width: 120

###############################################################################
#### R-RANSAC Node

# general
rransac/meas_time_window: 5
rransac/transform_consensus_set: false

# motion model specific parameters
rransac/sigmaQ_pos: 1
rransac/sigmaQ_vel: 1

# cluster parameters
rransac/cluster_time_threshold: 1
rransac/cluster_velocity_threshold: 2
rransac/cluster_position_threshold: 2
rransac/cluster_min_size_requirement: 5


# RANSAC Parameters (track initializer parameters)
rransac/RANSAC_max_iters: 10
rransac/RANSAC_score_stopping_criteria: 15
rransac/RANSAC_score_minimum_requirement: 8
rransac/RANSAC_minimum_subset: 3

#Model Manager
rransac/track_good_model_threshold: 20
rransac/track_max_missed_detection_time: 3
rransac/track_similar_tracks_threshold: 1
rransac/track_max_num_tracks: 10

#Nonlinear LMLE
rransac/nonlinear_innov_cov_id: false